const mongoose = require('mongoose')

const flogData = new mongoose.Schema({
    idFromUser: {type: mongoose.Schema.Types.ObjectId, ref: 'UserSchema'},
    sleepTime: {type: String},
    wakeTime: {type: String},
    sleepHours: {type: Number},
    moodOptions: {type: String},
    wakeAmt: {type: Number},
    physicalAct1: {type: String},
    physicalAct2: {type: String},
    physicalAct3: {type: String},
    physicalAct4: {type: String},
    physicalAct5: {type: String},
    typeOfPa1: {type: String},
    typeOfPa2: {type: String},
    typeOfPa3: {type: String},
    typeOfPa4: {type: String},
    typeOfPa5: {type: String},
    intensity1: {type: String},
    intensity2: {type: String},
    intensity3: {type: String},
    intensity4: {type: String},
    intensity5: {type: String},
    duration1: {type: Number},
    duration2: {type: Number},
    duration3: {type: Number},
    duration4: {type: Number},
    duration5: {type: Number},
    calorieBurned1: {type: Number},
    calorieBurned2: {type: Number},
    calorieBurned3: {type: Number},
    calorieBurned4: {type: Number},
    calorieBurned5: {type: Number},
    numSteps: {type: Number},
    totalCaloriesBurned: {type: Number},
    foodTime1: {type: String},
    foodTime2: {type: String},
    foodTime3: {type: String},
    foodTime4: {type: String},
    foodTime5: {type: String},
    meal1: {type: String},
    meal2: {type: String},
    meal3: {type: String},
    meal4: {type: String},
    meal5: {type: String},
    beverage1: {type: String},
    beverage2: {type: String},
    beverage3: {type: String},
    beverage4: {type: String},
    beverage5: {type: String},
    totalCalories1: {type: Number},
    totalCalories2: {type: Number},
    totalCalories3: {type: Number},
    totalCalories4: {type: Number},
    totalCalories5: {type: Number},
    deficitOrSurplus: {type: String},
    grade: {type: Number},
    feedback: {type: String}
},
{collection: 'user-logs'}
)

const model = mongoose.model('flogData', flogData)

module.exports = model